name: Test

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
  
      - name: Test SSH connection to AWS EC2
        env:
          HOST: 0.tcp.ngrok.io
          USER: ubuntu
          KEY: ${{ secrets.EC2_SSH_KEY}}
        run: |
          ssh  $USER@$HOST "echo 'SSH connection successful'"
